### ISSUE TITLE
could you make the git tags consistent?

### ISSUE THREAD

**Issue by hubutui** [dylan-profiler/visions#106]
Glad to know 0.5.0 is released. It seems that there is a typo in the tag? I believe you mean "0.5.0", not "0.50", see https://github.com/dylan-profiler/visions/tags. Also, it would help me a lot for auto packaging for ArchLinux if you could make the tag name consistent. The pattern "v${version}" would be great, for example.

**Comment by ieaves** [comment]
They say don't release on a Friday, at least in my case I should probably add don't release while your dog is pleading for a walk.

Thank you for the issue and apologies, the release tag should be fixed now.
