### ISSUE TITLE
all nulls should be inferred as generic

### ISSUE THREAD

**Issue by majidaldo** [dylan-profiler/visions#136]
i don't think this should be expected behavior.
```
In [41]: infer_type(pd.DataFrame({'x':['', '']}), StandardSet())
Out[41]: {'x': DateTime}

In [39]: infer_type(pd.DataFrame({'x':[None, None]}), StandardSet())
Out[39]: {'x': Boolean}
```

**Comment by sbrugman** [comment]
@majidaldo Thank you for reporting, these cases weren't handled properly indeed. 

Sequences consisting of _null_ values (e.g. `np.nan`, `pd.NaT`, `None`) will be of type `Generic` from now on.
The sequence of strings with length 0 will be of type `String` (users can of course override this behaviour).

**Comment by majidaldo** [comment]
Thanks. And pd.NA?

**Comment by sbrugman** [comment]
`pd.NA` is also covered, working on the release now.
