### ISSUE TITLE
Outdated online documentation

### ISSUE THREAD

**Issue by 1313e** [dylan-profiler/visions#21]
(This is part of the review in openjournals/joss-reviews#2145)

The online documentation at the moment mentions that the version is v0.2.1, while the latest version on PyPI is v0.2.3.
Can the online documentation please be updated to the same version as the released package?

**Comment by sbrugman** [comment]
Hi Ellert,

Thank you for reporting this issue. We've updated the docs in #19 and will update the package together with the first round of joss feedback.
