### ISSUE TITLE
API and Usage

### ISSUE THREAD

**Issue by 1313e** [dylan-profiler/visions#22]
(This is part of the review in openjournals/joss-reviews#2145)

Hi @sbrugman,

I am currently going through the package and I found it a very interesting project.
The type inference that already exists in built-in Python is frequently not enough, and I often find myself writing my own functions for it on a case-by-case basis.
So, it is nice to see that this is being done.

However, I do find myself having quite a bit of trouble using the package effectively.
Funnily enough, this is mostly caused by the (in my opinion) confusing naming schemes and the structure of the namespace.
It may require a bit of effort to solve (not to mention that it might create incompatibilities with previous versions), but I believe that it will greatly improve the user experience when fixed.

So, the main problem in my opinion is that almost all definitions are stored in their own subpackages in the `visions.core` subpackage, often separated as well over an `implementations` and a `model` subpackage.
This means that in order to access a definition, let's say `VisionsTypeset`, I have to import this from `visions.core.model.typeset`, while pre-defined typesets I have to import from `visions.core.implementations.typesets`.
In my opinion, it is incredibly confusing that these are stored in different subpackages/submodules, as they are related to the same thing, namely typesets, and I would expect to find all of these definitions in a `visions.typesets` subpackage.
Preferably, all definitions the average user would use, should be available either at root (`visions`) or a single level deep (`visions.xxx`).

I also noticed that almost all definitions have the word `visions` in their name.
I get the feeling that the reason for this is to avoid namespace clashes when someone uses a wildcard import (`from visions import *`).
However, as wildcard imports are heavily discouraged in the community, this leads to the user writing the word `visions` at least twice for every definition used (for example, using the `visions_integer` type requires me to write `visions.visions_integer`, which could be simplified to `visions.integer` or even `visions.int`).

Finally, I am not entirely sure if this has to do with the online documentation being outdated as mentioned in #21, but according to the example [here](https://dylan-profiler.github.io/visions/visions/getting_started/usage/typesets.html#detection), a `visions_standard_set` object has a method called `detect_type_series`.
In v0.2.3, this object neither has a method called `detect_type_series` nor `type_detect_series` (the name that the stand-alone function has in `visions.core.functional`), but instead it is called `detect_series_type`.
If possible, could you check and make sure that the methods and stand-alone functions use consistent naming schemes?

Please let me know if you have any questions.

**Comment by sbrugman** [comment]
Hi @1313e,

Great to hear you like our project.

Thanks for your extensive feedback. I agree that we can improve the user interface. The rationale behind distinguishing between the framework (model) and predefined types was the anticipation of additional typesets (statistics, finance) that are possibly incompatible with current definitions. In retrospect, we can hugely simplify this. Your point about class naming also makes sense.

The documentation should be updated. The expected behaviour is to allow both OO and functional styles: `typeset.detect_series_type(series)` and `detect_series_type(typeset, series)`.

**Comment by 1313e** [comment]
You could invert the logic a bit, by for example for the typesets, make a subpackage called `visions.typesets.core.implementations` and `visions.typesets.core.model`.
This way, you can keep the structure you already have, but you can make sure that everything is available under `visions.typesets`.
Then, for the user, it does not really matter what the underlying structure is, as long as it is under `visions.typesets`.

**Comment by sbrugman** [comment]
If I'm not mistaken, all points in this issue are addressed. The docs are here:
https://dylan-profiler.github.io/visions/visions/getting_started/usage/import.html

Thanks again!
I'll rerender the paper at the JOSS review when all PRs are merged.

**Comment by 1313e** [comment]
Hi @sbrugman,

this looks really great now, exactly as I meant.
It makes it much easier to find your way around the package.

One side note, that you may want to incorporate (not necessary however): Currently, both the module and the class contained in that module show up in `visions.typesets`, `visions.types`, etc.
You can hide the modules by renaming them such that they start with an underscore, like renaming `visions.types.integer` to `visions.types._integer`.
As the only definition the user ever needs from this module is `Integer`, which is already imported into the `visions.types` subpackage, an average user will never need to access the module it came from.
So, you can opt into hiding it.

Keep in mind that this is a minor thing and absolutely not required.
It simply cleans up the namespace of the package a bit.

Besides that, excellent job on improving the package namespace!

**Comment by 1313e** [comment]
After looking at the docs again, I see that the last point that I mentioned has not been resolved yet.
Currently, the example [here](https://dylan-profiler.github.io/visions/visions/getting_started/usage/typesets.html#detection) still mentions the use of `detect_type_series`, whereas the `VisionsTypeset` class uses `detect_series_type`.
It is also still inconsistent with the function used from `visions.functional` (`type_detect_series`).

**Comment by sbrugman** [comment]
> Hi @sbrugman,
> 
> this looks really great now, exactly as I meant.
> It makes it much easier to find your way around the package.
> 
> One side note, that you may want to incorporate (not necessary however): Currently, both the module and the class contained in that module show up in `visions.typesets`, `visions.types`, etc.
> You can hide the modules by renaming them such that they start with an underscore, like renaming `visions.types.integer` to `visions.types._integer`.
> As the only definition the user ever needs from this module is `Integer`, which is already imported into the `visions.types` subpackage, an average user will never need to access the module it came from.
> So, you can opt into hiding it.
> 
> Keep in mind that this is a minor thing and absolutely not required.
> It simply cleans up the namespace of the package a bit.
> 
> Besides that, excellent job on improving the package namespace!

Certainly, there are modules that do not have to be accessible to the user. Moreover, there are certain modules that are problematic when imported in the user's namespace (e.g. `from visions.types import float` would overwrite the buildin float). 

From my point of view, there is a simpler solution. We can specify `__all__` in `__init__.py` files: https://docs.python.org/3/tutorial/modules.html#importing-from-a-package. Surely, there is a tradeoff between renaming each file and keeping the `__all__` lists up to date.

**Comment by 1313e** [comment]
Correct, that is another way to do it.
Currently however, the class is correctly named `Float` and therefore does not clash with the built-in `float` type (but the module in which this class lives, does obviously).
Also, if someone executes `from visions.types import float`, they kind of made that mistake by themselves.
It is not really the job of the programmer to avoid potential namespace clashes that are extremely easy to avoid by the user itself.
Common Python coding practice is also to never import any definition from a namespace, but instead import the namespace itself (in this case `visions`) and access all definitions from there.

Keep however in mind that not putting the modules in `__all__` does not mean that they aren't imported and therefore accessible by the user.
The `__all__` dunder attribute is solely used for determining what definitions should be imported when someone performs a wildcard import.
It therefore is important to have one to avoid importing more than is necessary, but the `float` module will still be available as `visions.types.float` regardless of it being in any `__all__` declaration.
