### ISSUE TITLE
Inconsistent PyPI and docs versions

### ISSUE THREAD

**Issue by 1313e** [dylan-profiler/visions#29]
I see that the docs have been updated to be streamlined with the current version on `master` (v0.3.0), but currently, this version is not on PyPI (v0.2.3).
I am assuming that this is because you want v0.3.0 to be the version that coincides with the JOSS paper and therefore only deploy it on PyPI when the review is finished (which is a great idea).

However, something you may want to consider doing, is letting Travis CI perform the PyPI deployment for you.
You can read the [Travis CI docs](https://docs.travis-ci.com/user/deployment/pypi/) and my `.travis.yml` file in [CMasher](https://github.com/1313e/CMasher/blob/master/.travis.yml) for an example on how to do this.

Note that this is not part of the JOSS review, but simply some advice to keep the versions of `visions` streamlined everywhere.

**Comment by sbrugman** [comment]
The version on PyPi is now up-to-date.

Thanks for the suggestion, CMasher looks like a really cool project.

**Comment by 1313e** [comment]
Ah. I didn't mention CMasher to draw your attention to it, but simply because it has the easiest `.travis.yml` file of all packages that I have.
Still happy that you find it interesting though. :smile:
