### ISSUE TITLE
Improve community guidelines

### ISSUE THREAD

**Issue by 1313e** [dylan-profiler/visions#30]
(This is part of the review in openjournals/joss-reviews#2145)

Currently, the community guidelines [here](https://dylan-profiler.github.io/visions/visions/contributing/contributing.html) show what is expected if someone wants to contribute to the software (which is well done).
However, it currently does not mention how someone can seek support if they have issues with the software (like, by opening a GitHub issue).
Would be great if this could be added.

**Comment by sbrugman** [comment]
Agreed. There is now a dedicated support page:
https://dylan-profiler.github.io/visions/visions/contributing/support.html
