### ISSUE TITLE
No module named 'shapely'

### ISSUE THREAD

**Issue by 1313e** [dylan-profiler/visions#31]
(This is part of the review in openjournals/joss-reviews#2145)

When I try to execute the example given [here](https://dylan-profiler.github.io/visions/visions/getting_started/examples/casting.html#casting-example), I get an error stating `No module named 'shapely'`.
I see that this is a dependency of `visions`, but is only listed in the [`requirements_test.txt`](https://github.com/dylan-profiler/visions/blob/master/requirements_test.txt).
You probably have to add this requirement to the `requirements.txt` as well.

PS: Currently, the requirements of the package are both listed in their own separate file and in the `setup.py` file.
To avoid confusion for yourself, it is probably better to only use either.
You can read in a requirements file and use it in the `setup.py` file by using:
```python
# Get the requirements list
with open('requirements.txt', 'r') as f:
    requirements = f.read().splitlines()
```

Keep in mind that it is possible to link different requirements files together.
For example, you can link `requirements.txt` and `requirements_dev.txt` together by adding the line `-r requirements.txt` to the top of `requirements_dev.txt`.
This means that installing the requirements of `requirements_dev.txt` will use both files.
This however won't work if you parse the file in a `setup.py` file.
In that case, you can simply read both files and append them together if necessary.

**Comment by sbrugman** [comment]
To be able to use the `CompleteTypeset`, there are additional dependencies:

```pip install visions[type_geometry]```
(more information https://dylan-profiler.github.io/visions/visions/getting_started/installation.html)

The loading of the requirements could be more efficient. The pending PR #27 contains some improvements already.

**Comment by 1313e** [comment]
The example in the documentation does not mention that the additional dependencies are required for that example.
Also, you may want to avoid having several optional additional dependencies for your package, as that is very confusing for average users.
As long as a package is not incredibly big (like `PyQt5`) or hard to install (like `mpi4py`), you could opt for simply installing it by default as long as it is not solely used for testing.

**Comment by sbrugman** [comment]
The default installation instructions include all dependencies (```pip install visions[all]```), for which all examples work. We chose to make `visions` lightweight by default as it is included in the dependency tree of a frequently downloaded package.

For future reference, we are raising an exception when instantiating a typeset when dependencies are missing.

> ValueError: This typeset requires dependencies that are currently not installed (No module named 'shapely'). You can follow the installation instructions to resolve this issue: https://dylan-profiler.github.io/visions/visions/getting_started/installation.html

**Comment by 1313e** [comment]
That is also a fine solution. :+1:
