### ISSUE TITLE
Automate PyPi deployment

### ISSUE THREAD

**Issue by sbrugman** [dylan-profiler/visions#44]
Provided that we extended the testing to make sure that the source builds a valid Pypi package, we can move on to automate the PyPi deployment. I suggest we use Travis CI for that (https://docs.travis-ci.com/user/deployment/pypi/). In addition to the code changes, we need to setup the branching to prevent the deployment of development code.

**Comment by ieaves** [comment]
Geat idea. We could do a simple git flow dev branch with merges to master representing a release?

**Comment by sbrugman** [comment]
Perfect. We can tag the code at each release with [github releases](https://github.com/dylan-profiler/visions/releases).
