### ISSUE TITLE
Automate building of documentation

### ISSUE THREAD

**Issue by sbrugman** [dylan-profiler/visions#45]
The documentation should rebuilt at every merge. The differences caused by the documentation convolute code reviews. The steps to build the documentation are simple and can be automated.

Suggested solution via Github Actions (e.g.):
https://github.com/marketplace/actions/sphinx-build
https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml

**Comment by ieaves** [comment]
We have a bunch of previous commits that included code changes and unrelated documentation changes leading to 100's of changed files (corresponding to documentation) and then a few code changes. This made code review substantially more difficult. 

We will need to practice more discipline moving forwards if doc rebuilds are part of the default workflow.

**Comment by sbrugman** [comment]
If I understand correctly, the documentation is built by Github actions online without our involvement. See https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml#L45

**Comment by ieaves** [comment]
It's still running a `git add .`, `git commit` so the action itself is to add an additional commit which represents the documentation changes. If you view the diff on a PR it will include all changed documentation alongside the code changes. This isn't a big deal so long as changes to documentation are only related to changes in the code but can become a big pain if not.

**Comment by sbrugman** [comment]
Using the `on` instruction, it's possible to restrict it to specific branches. We could have one branch for development (without docs) to solve this, right?

```
on:
  push:
    branches:    
      - master
```

**Comment by ieaves** [comment]
Yes!

**Comment by sbrugman** [comment]
Github Actions now runs on the master branch. It automatically formats code, renders the diagrams and builds the documentation. If anything has changed, it commits those changes back to the master.
