### ISSUE TITLE
Typeset types regression

### ISSUE THREAD

**Issue by ieaves** [dylan-profiler/visions#85]
It appears possible to introduce undesired types into a typesets relation_graph without warning or error.

Steps to reproduce:

```

class ProfilingTypeSet(VisionsTypeset):
    """Base typeset for pandas-profiling"""
    def __init__(self):
        types = {
            Categorical,
            Boolean,
            Float,
            DateTime,
            URL,
            Complex,
            Path,
            File,
            Image,
            Integer,
            Object
        }
        super().__init__(types)

pp_typeset = ProfilingTypeSet()
```

Note `String` is not included in this typeset, and yet:

```
pp_typeset.types
>> {Boolean,
 Categorical,
 Complex,
 DateTime,
 File,
 Float,
 Generic,
 Image,
 Integer,
 Object,
 Path,
 String,
 URL}
```

and
<img width="930" alt="Screen Shot 2020-06-28 at 11 35 03 AM" src="https://user-images.githubusercontent.com/7785207/85953144-eda97d80-b933-11ea-8587-8a5540557ff7.png">

**Comment by sbrugman** [comment]
@ieaves: The user gets warned that there are relations from a type that is not in the typeset. 

> (...)\visions\typesets\typeset.py:36: UserWarning: Provided relations included mapping from String to Float but String was not included in the provided list of nodes
  related_type=relation.related_type, own_type=relation.type
(...)\visions\typesets\typeset.py:36: UserWarning: Provided relations included mapping from String to URL but String was not included in the provided list of nodes
  related_type=relation.related_type, own_type=relation.type
(...)\visions\typesets\typeset.py:36: UserWarning: Provided relations included mapping from String to Path but String was not included in the provided list of nodes
  related_type=relation.related_type, own_type=relation.type
(...)\visions\typesets\typeset.py:36: UserWarning: Provided relations included mapping from String to DateTime but String was not included in the provided list of nodes
  related_type=relation.related_type, own_type=relation.type
(...)\visions\typesets\typeset.py:36: UserWarning: Provided relations included mapping from String to Boolean but String was not included in the provided list of nodes
  related_type=relation.related_type, own_type=relation.type
(...)\visions\typesets\typeset.py:36: UserWarning: Provided relations included mapping from String to Complex but String was not included in the provided list of nodes
  related_type=relation.related_type, own_type=relation.type

We could be more strict by making this an error when this is the case or we could change the graph structure as expected and remove the node from the graph (in this case `String`). My preference would go to the latter option.
