### ISSUE TITLE
Error Encounter in examples notebook.

### ISSUE THREAD

**Issue by liyzcj** [dylan-profiler/visions#97]
**Describe the bug**

When I run the given example notebook,  It will raise TypeError when call `cast_frame(df, typeset)`:

```python
TypeError: Only str is accepted.
```

**To Reproduce**
1. Run the titanic.ipynb in examples.

**Expected behavior**
The cast_frame should not raise exceptions in that case.

**Additional context**

I think the problem happend because relation mappting between `Object` and `Geometry`. The `wkt.loads` only accept string value.

**Comment by ieaves** [comment]
Thank you, this was also fixed in #100

**Comment by ieaves** [comment]
Resolved by #100
